// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: apiservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TunnlrxApiServeice_CreateClient_FullMethodName = "/proto.TunnlrxApiServeice/CreateClient"
	TunnlrxApiServeice_CreateTunnel_FullMethodName = "/proto.TunnlrxApiServeice/CreateTunnel"
)

// TunnlrxApiServeiceClient is the client API for TunnlrxApiServeice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnlrxApiServeiceClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	CreateTunnel(ctx context.Context, in *CreateTunnelRequest, opts ...grpc.CallOption) (*CreateTunnelResponse, error)
}

type tunnlrxApiServeiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnlrxApiServeiceClient(cc grpc.ClientConnInterface) TunnlrxApiServeiceClient {
	return &tunnlrxApiServeiceClient{cc}
}

func (c *tunnlrxApiServeiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, TunnlrxApiServeice_CreateClient_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnlrxApiServeiceClient) CreateTunnel(ctx context.Context, in *CreateTunnelRequest, opts ...grpc.CallOption) (*CreateTunnelResponse, error) {
	out := new(CreateTunnelResponse)
	err := c.cc.Invoke(ctx, TunnlrxApiServeice_CreateTunnel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnlrxApiServeiceServer is the server API for TunnlrxApiServeice service.
// All implementations should embed UnimplementedTunnlrxApiServeiceServer
// for forward compatibility
type TunnlrxApiServeiceServer interface {
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	CreateTunnel(context.Context, *CreateTunnelRequest) (*CreateTunnelResponse, error)
}

// UnimplementedTunnlrxApiServeiceServer should be embedded to have forward compatible implementations.
type UnimplementedTunnlrxApiServeiceServer struct {
}

func (UnimplementedTunnlrxApiServeiceServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedTunnlrxApiServeiceServer) CreateTunnel(context.Context, *CreateTunnelRequest) (*CreateTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTunnel not implemented")
}

// UnsafeTunnlrxApiServeiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnlrxApiServeiceServer will
// result in compilation errors.
type UnsafeTunnlrxApiServeiceServer interface {
	mustEmbedUnimplementedTunnlrxApiServeiceServer()
}

func RegisterTunnlrxApiServeiceServer(s grpc.ServiceRegistrar, srv TunnlrxApiServeiceServer) {
	s.RegisterService(&TunnlrxApiServeice_ServiceDesc, srv)
}

func _TunnlrxApiServeice_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnlrxApiServeiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnlrxApiServeice_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnlrxApiServeiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnlrxApiServeice_CreateTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnlrxApiServeiceServer).CreateTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnlrxApiServeice_CreateTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnlrxApiServeiceServer).CreateTunnel(ctx, req.(*CreateTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TunnlrxApiServeice_ServiceDesc is the grpc.ServiceDesc for TunnlrxApiServeice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnlrxApiServeice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TunnlrxApiServeice",
	HandlerType: (*TunnlrxApiServeiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _TunnlrxApiServeice_CreateClient_Handler,
		},
		{
			MethodName: "CreateTunnel",
			Handler:    _TunnlrxApiServeice_CreateTunnel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiservice.proto",
}
