// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientState int32

const (
	ClientState_CLIENT_STATE_UNKNOWN     ClientState = 0
	ClientState_CLIENT_STATE_ACTIVE      ClientState = 1
	ClientState_CLIENT_STATE_IN_ACTIVE   ClientState = 2
	ClientState_CLIENT_STATE_IN_PROGRESS ClientState = 3
)

// Enum value maps for ClientState.
var (
	ClientState_name = map[int32]string{
		0: "CLIENT_STATE_UNKNOWN",
		1: "CLIENT_STATE_ACTIVE",
		2: "CLIENT_STATE_IN_ACTIVE",
		3: "CLIENT_STATE_IN_PROGRESS",
	}
	ClientState_value = map[string]int32{
		"CLIENT_STATE_UNKNOWN":     0,
		"CLIENT_STATE_ACTIVE":      1,
		"CLIENT_STATE_IN_ACTIVE":   2,
		"CLIENT_STATE_IN_PROGRESS": 3,
	}
)

func (x ClientState) Enum() *ClientState {
	p := new(ClientState)
	*p = x
	return p
}

func (x ClientState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ClientState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ClientState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientState.Descriptor instead.
func (ClientState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type TunnelState int32

const (
	TunnelState_TUNNEL_STATE_UNKNOWN     TunnelState = 0
	TunnelState_TUNNEL_STATE_ACTIVE      TunnelState = 1
	TunnelState_TUNNEL_STATE_IN_ACTIVE   TunnelState = 2
	TunnelState_TUNNEL_STATE_IN_PROGRESS TunnelState = 3
)

// Enum value maps for TunnelState.
var (
	TunnelState_name = map[int32]string{
		0: "TUNNEL_STATE_UNKNOWN",
		1: "TUNNEL_STATE_ACTIVE",
		2: "TUNNEL_STATE_IN_ACTIVE",
		3: "TUNNEL_STATE_IN_PROGRESS",
	}
	TunnelState_value = map[string]int32{
		"TUNNEL_STATE_UNKNOWN":     0,
		"TUNNEL_STATE_ACTIVE":      1,
		"TUNNEL_STATE_IN_ACTIVE":   2,
		"TUNNEL_STATE_IN_PROGRESS": 3,
	}
)

func (x TunnelState) Enum() *TunnelState {
	p := new(TunnelState)
	*p = x
	return p
}

func (x TunnelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (TunnelState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x TunnelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelState.Descriptor instead.
func (TunnelState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	ClientState   ClientState            `protobuf:"varint,5,opt,name=client_state,json=clientState,proto3,enum=proto.ClientState" json:"client_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Client) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Client) GetClientState() ClientState {
	if x != nil {
		return x.ClientState
	}
	return ClientState_CLIENT_STATE_UNKNOWN
}

type Tunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Client        *Client                `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	TunnelState   TunnelState            `protobuf:"varint,6,opt,name=tunnel_state,json=tunnelState,proto3,enum=proto.TunnelState" json:"tunnel_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Tunnel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Tunnel) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Tunnel) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Tunnel) GetTunnelState() TunnelState {
	if x != nil {
		return x.TunnelState
	}
	return TunnelState_TUNNEL_STATE_UNKNOWN
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x05proto\"\x87\x01\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x125\n" +
	"\fclient_state\x18\x05 \x01(\x0e2\x12.proto.ClientStateR\vclientState\"\xb6\x01\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12%\n" +
	"\x06client\x18\x05 \x01(\v2\r.proto.ClientR\x06client\x125\n" +
	"\ftunnel_state\x18\x06 \x01(\x0e2\x12.proto.TunnelStateR\vtunnelState*z\n" +
	"\vClientState\x12\x18\n" +
	"\x14CLIENT_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13CLIENT_STATE_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16CLIENT_STATE_IN_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18CLIENT_STATE_IN_PROGRESS\x10\x03*z\n" +
	"\vTunnelState\x12\x18\n" +
	"\x14TUNNEL_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13TUNNEL_STATE_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16TUNNEL_STATE_IN_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18TUNNEL_STATE_IN_PROGRESS\x10\x03B3Z1github.com/eyanshu1997/tunnlrX/common/proto;protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(ClientState)(0), // 0: proto.ClientState
	(TunnelState)(0), // 1: proto.TunnelState
	(*Client)(nil),   // 2: proto.Client
	(*Tunnel)(nil),   // 3: proto.Tunnel
}
var file_common_proto_depIdxs = []int32{
	0, // 0: proto.Client.client_state:type_name -> proto.ClientState
	2, // 1: proto.Tunnel.client:type_name -> proto.Client
	1, // 2: proto.Tunnel.tunnel_state:type_name -> proto.TunnelState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
