// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientState int32

const (
	ClientState_CLIENT_STATE_UNKNOWN     ClientState = 0
	ClientState_CLIENT_STATE_ACTIVE      ClientState = 1
	ClientState_CLIENT_STATE_IN_ACTIVE   ClientState = 2
	ClientState_CLIENT_STATE_IN_PROGRESS ClientState = 3
)

// Enum value maps for ClientState.
var (
	ClientState_name = map[int32]string{
		0: "CLIENT_STATE_UNKNOWN",
		1: "CLIENT_STATE_ACTIVE",
		2: "CLIENT_STATE_IN_ACTIVE",
		3: "CLIENT_STATE_IN_PROGRESS",
	}
	ClientState_value = map[string]int32{
		"CLIENT_STATE_UNKNOWN":     0,
		"CLIENT_STATE_ACTIVE":      1,
		"CLIENT_STATE_IN_ACTIVE":   2,
		"CLIENT_STATE_IN_PROGRESS": 3,
	}
)

func (x ClientState) Enum() *ClientState {
	p := new(ClientState)
	*p = x
	return p
}

func (x ClientState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ClientState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ClientState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientState.Descriptor instead.
func (ClientState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type TunnelState int32

const (
	TunnelState_TUNNEL_STATE_UNKNOWN     TunnelState = 0
	TunnelState_TUNNEL_STATE_ACTIVE      TunnelState = 1
	TunnelState_TUNNEL_STATE_IN_ACTIVE   TunnelState = 2
	TunnelState_TUNNEL_STATE_IN_PROGRESS TunnelState = 3
)

// Enum value maps for TunnelState.
var (
	TunnelState_name = map[int32]string{
		0: "TUNNEL_STATE_UNKNOWN",
		1: "TUNNEL_STATE_ACTIVE",
		2: "TUNNEL_STATE_IN_ACTIVE",
		3: "TUNNEL_STATE_IN_PROGRESS",
	}
	TunnelState_value = map[string]int32{
		"TUNNEL_STATE_UNKNOWN":     0,
		"TUNNEL_STATE_ACTIVE":      1,
		"TUNNEL_STATE_IN_ACTIVE":   2,
		"TUNNEL_STATE_IN_PROGRESS": 3,
	}
)

func (x TunnelState) Enum() *TunnelState {
	p := new(TunnelState)
	*p = x
	return p
}

func (x TunnelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (TunnelState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x TunnelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelState.Descriptor instead.
func (TunnelState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x05proto*z\n" +
	"\vClientState\x12\x18\n" +
	"\x14CLIENT_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13CLIENT_STATE_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16CLIENT_STATE_IN_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18CLIENT_STATE_IN_PROGRESS\x10\x03*z\n" +
	"\vTunnelState\x12\x18\n" +
	"\x14TUNNEL_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13TUNNEL_STATE_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16TUNNEL_STATE_IN_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18TUNNEL_STATE_IN_PROGRESS\x10\x03B3Z1github.com/eyanshu1997/tunnlrX/common/proto;protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_goTypes = []any{
	(ClientState)(0), // 0: proto.ClientState
	(TunnelState)(0), // 1: proto.TunnelState
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
