// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientState int32

const (
	ClientState_ClientStateUnknown    ClientState = 0
	ClientState_ClientStateActive     ClientState = 1
	ClientState_ClientStateInActive   ClientState = 2
	ClientState_ClientStateInProgress ClientState = 3
)

// Enum value maps for ClientState.
var (
	ClientState_name = map[int32]string{
		0: "ClientStateUnknown",
		1: "ClientStateActive",
		2: "ClientStateInActive",
		3: "ClientStateInProgress",
	}
	ClientState_value = map[string]int32{
		"ClientStateUnknown":    0,
		"ClientStateActive":     1,
		"ClientStateInActive":   2,
		"ClientStateInProgress": 3,
	}
)

func (x ClientState) Enum() *ClientState {
	p := new(ClientState)
	*p = x
	return p
}

func (x ClientState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_config_proto_enumTypes[0].Descriptor()
}

func (ClientState) Type() protoreflect.EnumType {
	return &file_common_proto_config_proto_enumTypes[0]
}

func (x ClientState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientState.Descriptor instead.
func (ClientState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_config_proto_rawDescGZIP(), []int{0}
}

type RegisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_common_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_common_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClientResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterClientResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_common_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_config_proto_rawDescGZIP(), []int{2}
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=Clients,proto3" json:"Clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_common_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	ClientState   ClientState            `protobuf:"varint,6,opt,name=ClientState,proto3,enum=proto.ClientState" json:"ClientState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_common_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_common_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *Client) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Client) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Client) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Client) GetClientState() ClientState {
	if x != nil {
		return x.ClientState
	}
	return ClientState_ClientStateUnknown
}

var File_common_proto_config_proto protoreflect.FileDescriptor

const file_common_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x19common/proto/config.proto\x12\x05proto\"+\n" +
	"\x15RegisterClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x16RegisterClientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\x14\n" +
	"\x12ListClientsRequest\">\n" +
	"\x13ListClientsResponse\x12'\n" +
	"\aClients\x18\x01 \x03(\v2\r.proto.ClientR\aClients\"\x9e\x01\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x124\n" +
	"\vClientState\x18\x06 \x01(\x0e2\x12.proto.ClientStateR\vClientState*p\n" +
	"\vClientState\x12\x16\n" +
	"\x12ClientStateUnknown\x10\x00\x12\x15\n" +
	"\x11ClientStateActive\x10\x01\x12\x17\n" +
	"\x13ClientStateInActive\x10\x02\x12\x19\n" +
	"\x15ClientStateInProgress\x10\x032\xa4\x01\n" +
	"\rConfigService\x12M\n" +
	"\x0eRegisterClient\x12\x1c.proto.RegisterClientRequest\x1a\x1d.proto.RegisterClientResponse\x12D\n" +
	"\vListClients\x12\x19.proto.ListClientsRequest\x1a\x1a.proto.ListClientsResponseB3Z1github.com/eyanshu1997/tunnlrX/common/proto;protob\x06proto3"

var (
	file_common_proto_config_proto_rawDescOnce sync.Once
	file_common_proto_config_proto_rawDescData []byte
)

func file_common_proto_config_proto_rawDescGZIP() []byte {
	file_common_proto_config_proto_rawDescOnce.Do(func() {
		file_common_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_config_proto_rawDesc), len(file_common_proto_config_proto_rawDesc)))
	})
	return file_common_proto_config_proto_rawDescData
}

var file_common_proto_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_config_proto_goTypes = []any{
	(ClientState)(0),               // 0: proto.ClientState
	(*RegisterClientRequest)(nil),  // 1: proto.RegisterClientRequest
	(*RegisterClientResponse)(nil), // 2: proto.RegisterClientResponse
	(*ListClientsRequest)(nil),     // 3: proto.ListClientsRequest
	(*ListClientsResponse)(nil),    // 4: proto.ListClientsResponse
	(*Client)(nil),                 // 5: proto.Client
}
var file_common_proto_config_proto_depIdxs = []int32{
	5, // 0: proto.ListClientsResponse.Clients:type_name -> proto.Client
	0, // 1: proto.Client.ClientState:type_name -> proto.ClientState
	1, // 2: proto.ConfigService.RegisterClient:input_type -> proto.RegisterClientRequest
	3, // 3: proto.ConfigService.ListClients:input_type -> proto.ListClientsRequest
	2, // 4: proto.ConfigService.RegisterClient:output_type -> proto.RegisterClientResponse
	4, // 5: proto.ConfigService.ListClients:output_type -> proto.ListClientsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_config_proto_init() }
func file_common_proto_config_proto_init() {
	if File_common_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_config_proto_rawDesc), len(file_common_proto_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_config_proto_goTypes,
		DependencyIndexes: file_common_proto_config_proto_depIdxs,
		EnumInfos:         file_common_proto_config_proto_enumTypes,
		MessageInfos:      file_common_proto_config_proto_msgTypes,
	}.Build()
	File_common_proto_config_proto = out.File
	file_common_proto_config_proto_goTypes = nil
	file_common_proto_config_proto_depIdxs = nil
}
