// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: common/proto/tunnel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelState int32

const (
	TunnelState_TunnelStateUnknown    TunnelState = 0
	TunnelState_TunnelStateUp         TunnelState = 1
	TunnelState_TunnelStateDown       TunnelState = 2
	TunnelState_TunnelStateInProgress TunnelState = 3
)

// Enum value maps for TunnelState.
var (
	TunnelState_name = map[int32]string{
		0: "TunnelStateUnknown",
		1: "TunnelStateUp",
		2: "TunnelStateDown",
		3: "TunnelStateInProgress",
	}
	TunnelState_value = map[string]int32{
		"TunnelStateUnknown":    0,
		"TunnelStateUp":         1,
		"TunnelStateDown":       2,
		"TunnelStateInProgress": 3,
	}
)

func (x TunnelState) Enum() *TunnelState {
	p := new(TunnelState)
	*p = x
	return p
}

func (x TunnelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (TunnelState) Type() protoreflect.EnumType {
	return &file_common_proto_tunnel_proto_enumTypes[0]
}

func (x TunnelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelState.Descriptor instead.
func (TunnelState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

type CreateTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelRequest) Reset() {
	*x = CreateTunnelRequest{}
	mi := &file_common_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelRequest) ProtoMessage() {}

func (x *CreateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelRequest.ProtoReflect.Descriptor instead.
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTunnelRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CreateTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelResponse) Reset() {
	*x = CreateTunnelResponse{}
	mi := &file_common_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelResponse) ProtoMessage() {}

func (x *CreateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelResponse.ProtoReflect.Descriptor instead.
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTunnelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTunnelResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_common_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*Tunnel              `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_common_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ListTunnelsResponse) GetTunnels() []*Tunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type Tunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	TunnelState   TunnelState            `protobuf:"varint,5,opt,name=tunnelState,proto3,enum=tunnel.TunnelState" json:"tunnelState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_common_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_common_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Tunnel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Tunnel) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Tunnel) GetTunnelState() TunnelState {
	if x != nil {
		return x.TunnelState
	}
	return TunnelState_TunnelStateUnknown
}

var File_common_proto_tunnel_proto protoreflect.FileDescriptor

const file_common_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x19common/proto/tunnel.proto\x12\x06tunnel\"=\n" +
	"\x13CreateTunnelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\">\n" +
	"\x14CreateTunnelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\x14\n" +
	"\x12ListTunnelsRequest\"?\n" +
	"\x13ListTunnelsResponse\x12(\n" +
	"\atunnels\x18\x01 \x03(\v2\x0e.tunnel.TunnelR\atunnels\"\x8f\x01\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x125\n" +
	"\vtunnelState\x18\x05 \x01(\x0e2\x13.tunnel.TunnelStateR\vtunnelState*h\n" +
	"\vTunnelState\x12\x16\n" +
	"\x12TunnelStateUnknown\x10\x00\x12\x11\n" +
	"\rTunnelStateUp\x10\x01\x12\x13\n" +
	"\x0fTunnelStateDown\x10\x02\x12\x19\n" +
	"\x15TunnelStateInProgress\x10\x032\xa2\x01\n" +
	"\rTunnelService\x12I\n" +
	"\fCreateTunnel\x12\x1b.tunnel.CreateTunnelRequest\x1a\x1c.tunnel.CreateTunnelResponse\x12F\n" +
	"\vListTunnels\x12\x1a.tunnel.ListTunnelsRequest\x1a\x1b.tunnel.ListTunnelsResponseB3Z1github.com/eyanshu1997/tunnlrX/common/proto;protob\x06proto3"

var (
	file_common_proto_tunnel_proto_rawDescOnce sync.Once
	file_common_proto_tunnel_proto_rawDescData []byte
)

func file_common_proto_tunnel_proto_rawDescGZIP() []byte {
	file_common_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_common_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_tunnel_proto_rawDesc), len(file_common_proto_tunnel_proto_rawDesc)))
	})
	return file_common_proto_tunnel_proto_rawDescData
}

var file_common_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_tunnel_proto_goTypes = []any{
	(TunnelState)(0),             // 0: tunnel.TunnelState
	(*CreateTunnelRequest)(nil),  // 1: tunnel.CreateTunnelRequest
	(*CreateTunnelResponse)(nil), // 2: tunnel.CreateTunnelResponse
	(*ListTunnelsRequest)(nil),   // 3: tunnel.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),  // 4: tunnel.ListTunnelsResponse
	(*Tunnel)(nil),               // 5: tunnel.Tunnel
}
var file_common_proto_tunnel_proto_depIdxs = []int32{
	5, // 0: tunnel.ListTunnelsResponse.tunnels:type_name -> tunnel.Tunnel
	0, // 1: tunnel.Tunnel.tunnelState:type_name -> tunnel.TunnelState
	1, // 2: tunnel.TunnelService.CreateTunnel:input_type -> tunnel.CreateTunnelRequest
	3, // 3: tunnel.TunnelService.ListTunnels:input_type -> tunnel.ListTunnelsRequest
	2, // 4: tunnel.TunnelService.CreateTunnel:output_type -> tunnel.CreateTunnelResponse
	4, // 5: tunnel.TunnelService.ListTunnels:output_type -> tunnel.ListTunnelsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_tunnel_proto_init() }
func file_common_proto_tunnel_proto_init() {
	if File_common_proto_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_tunnel_proto_rawDesc), len(file_common_proto_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_common_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_common_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_common_proto_tunnel_proto_msgTypes,
	}.Build()
	File_common_proto_tunnel_proto = out.File
	file_common_proto_tunnel_proto_goTypes = nil
	file_common_proto_tunnel_proto_depIdxs = nil
}
